# all: ece250_socket.cpp main_example.cpp
# 	g++ -std=c++11 ece250_socket.cpp main_example.cpp

all: ece250_socket.cpp main.cpp Trie.cpp Node.cpp
	g++ -std=c++11 ece250_socket.cpp main.cpp Trie.cpp Node.cpp